name: build and test 

on: push

jobs:
  build:
    runs-on: ubuntu-latest
  
    steps:
      - uses: actions/checkout@v2
      - name: Build using Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.7'
      
      - name: Install dependencies [pip]
        run: 
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run unit tests [pytest]
        run: pytest